import { v4 as uuidv4 } from "uuid";

export class Film {
    uuid: string = uuidv4();
    kpId?: number;
    externalKpHD?: string;
    externalImdb?: string;
    externalTmdb?: string;
    ratingKp?: number;
    ratingImdb?: number;
    ratingFilmCritics?: number;
    ratingRussianFilmCritics?: number;
    votesKp?: number;
    votesImdb?: number;
    votesFilmCritics?: number;
    votesRussianFilmCritics?: number;
    enImdbPoster?: string;
    uaImdbPoster?: string;
    ruImdbPoster?: string;
    posterUrl?: string;
    posterPreviewUrl?: string;
    externalId?: Record<string, string>;
    rating?: Record<string, string>;
    votes?: Record<string, string>;
    movieLength?: number;
    type?: string;
    name?: string;
    description?: string;
    year?: number;
    poster?: Record<string, string>;
    genres?: Record<string, string>[];
    countries?: Record<string, string>[];
    genresList?: string[];
    countriesList?: string[];
    alternativeName?: string;
    enName?: string;
    names?: Record<string, string>[];
    shortDescription?: string;
    releaseYears?: Record<string, number | null | undefined>[];
  }
